# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: despesasweb_development
  username: <%= ENV['DATABASE_DEVELOPMENT_USERNAME'] %> # Lendo do .env
  password: <%= ENV['DATABASE_DEVELOPMENT_PASSWORD'] %> # Lendo do .env
  host: <%= ENV['DATABASE_DEVELOPMENT_HOST'] || 'localhost' %> # Com fallback para 'localhost'
  port: <%= ENV['DATABASE_DEVELOPMENT_PORT'] || 5432 %>      # Com fallback para 5432

test:
  <<: *default
  database: despesasweb_test
  username: <%= ENV['DATABASE_TEST_USERNAME'] || ENV['DATABASE_DEVELOPMENT_USERNAME'] %> # Pode reusar dev ou ter suas próprias
  password: <%= ENV['DATABASE_TEST_PASSWORD'] || ENV['DATABASE_DEVELOPMENT_PASSWORD'] %>
  host: <%= ENV['DATABASE_TEST_HOST'] || ENV['DATABASE_DEVELOPMENT_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_TEST_PORT'] || ENV['DATABASE_DEVELOPMENT_PORT'] || 5432 %>

production:
  primary:
    <<: *default
    # Use DATABASE_URL se seu provedor de hospedagem fornecer uma única URL.
    # Ex: url: <%= ENV['DATABASE_PRIMARY_URL'] %>
    # Ou use as variáveis separadas, que serão lidas do ambiente do servidor:
    database: <%= ENV['DATABASE_PRIMARY_NAME'] %>
    username: <%= ENV['DATABASE_PRIMARY_USERNAME'] %>
    password: <%= ENV['DATABASE_PRIMARY_PASSWORD'] %>
    host: <%= ENV['DATABASE_PRIMARY_HOST'] %>
    port: <%= ENV['DATABASE_PRIMARY_PORT'] %>
  cache:
    <<: *default
    database: <%= ENV['DATABASE_CACHE_NAME'] %>
    username: <%= ENV['DATABASE_CACHE_USERNAME'] %>
    password: <%= ENV['DATABASE_CACHE_PASSWORD'] %>
    host: <%= ENV['DATABASE_CACHE_HOST'] %>
    port: <%= ENV['DATABASE_CACHE_PORT'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_NAME'] %>
    username: <%= ENV['DATABASE_QUEUE_USERNAME'] %>
    password: <%= ENV['DATABASE_QUEUE_PASSWORD'] %>
    host: <%= ENV['DATABASE_QUEUE_HOST'] %>
    port: <%= ENV['DATABASE_QUEUE_PORT'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_NAME'] %>
    username: <%= ENV['DATABASE_CABLE_USERNAME'] %>
    password: <%= ENV['DATABASE_CABLE_PASSWORD'] %>
    host: <%= ENV['DATABASE_CABLE_HOST'] %>
    port: <%= ENV['DATABASE_CABLE_PORT'] %>
    migrations_paths: db/cable_migrate